version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: focusflow-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./backend
    container_name: focusflow-server
    env_file:
      - ./backend/.env.${NODE_ENV:-development}  
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build: ./frontend
    container_name: focusflow-client
    env_file:
      - ./frontend/.env.${NODE_ENV:-development} 
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mongo_data: